spring.application.name=assistente-financeiro
server.port=8080

google.sheets.credentials-path=/home/ubuntu/credentials/google-service-account.json
google.sheets.spreadsheet-id=COLE_AQUI_O_ID_DA_PLANILHA
google.sheets.sheet-name=Acompanhamento


telegram.bot-token=COLE_AQUI_O_TOKEN_DO_BOTFATHER
telegram.webhook-secret=escolha-uma-senha-aqui
